services:
  db:
    image: postgres:15
    container_name: hackathon_back
    environment:
      - POSTGRES_DB=hackathon2025
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5450:5432"
    restart: always
